//----------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a EventWithParameter.tt
//     Changes will be lost if the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------

using DoubleEngine.AtomEvents;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DoubleEngine_xUnit
{
    public partial class EventWithParameter
    {
        [Fact]
        public void TestParemeter_AtomEvent()
        {
            testValue = 10;
            AtomEvent<int> eventInt = new();
            eventInt.Subscribe(Inc_TestValue);
            eventInt.Publish(5);
            Assert.Equal(15, testValue);
        }
    }
}
