//----------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Conversion_Matrix_To.tt. 
//     Changes will be lost if the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------

using UnityEngine;

namespace DoubleEngine.UHelpers;
public static partial class Conversion
{

    public static Matrix4x4 ToMatrix4x4(this MatrixD4x4 d) => 
        new Matrix4x4(
        new Vector4((float)d.m00, (float)d.m01, (float)d.m02, (float)d.m03),
        new Vector4((float)d.m10, (float)d.m11, (float)d.m12, (float)d.m13),
        new Vector4((float)d.m20, (float)d.m21, (float)d.m22, (float)d.m23),
        new Vector4((float)d.m30, (float)d.m31, (float)d.m32, (float)d.m33)
        );
    public static MatrixD4x4 ToMatrixD4x4(this Matrix4x4 u) => new MatrixD4x4(u.m00, u.m01, u.m02, u.m03, u.m10, u.m11, u.m12, u.m13, u.m20, u.m21, u.m22, u.m23, u.m30, u.m31, u.m32, u.m33);
 
        //public static MatrixD4x4 FromMatrix4x4(Matrix4x4 u) => new MatrixD4x4(u.m00, u.m01, u.m02, u.m03, u.m10, u.m11, u.m12, u.m13, u.m20, u.m21, u.m22, u.m23, u.m30, u.m31, u.m32, u.m33);
}