
//----------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Tri_To.tt
//     Changes will be lost if the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------

using System.Collections;
using System.Collections.Generic;

namespace DoubleEngine
{
    public static partial class TrigonHelpers
    {


        public static TriVec2D ToTriVec2D(this TriVec3D face) =>
            new TriVec2D( face.v0.ConvertXYZtoXY(), face.v1.ConvertXYZtoXY(), face.v2.ConvertXYZtoXY() );
        public static TriVec2D ToTriVec2D(this Vec3D v0, Vec3D v1, Vec3D v2) =>
            new TriVec2D( v0.ConvertXYZtoXY(), v1.ConvertXYZtoXY(), v2.ConvertXYZtoXY() );

            /*
        public static TriVec2D ToTriVec2D(this TriVector2 face) =>
            new TriVec2D( face.v0.ToVec2D(), face.v1.ToVec2D(), face.v2.ToVec2D() );
        public static TriVec2D ToTriVec2D(this Vector2 v0, Vector2 v1, Vector2 v2) =>
            new TriVec2D( v0.ToVec2D(), v1.ToVec2D(), v2.ToVec2D() );
            */


    }

}