//----------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes will be lost if the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace DoubleEngine
{
    public static partial class VectorUtil
    {
    public static Vec2D Last(this Vec2D[] vertices) =>
        vertices[vertices.Length - 1];
    public static Vec3D Last(this Vec3D[] vertices) =>
        vertices[vertices.Length - 1];
    public static Vec4D Last(this Vec4D[] vertices) =>
        vertices[vertices.Length - 1];
    }
}
